### PR TITLE
More changes regarding hasura config

### PR DESCRIPTION
**Pull request by 852Kerfunkle**

### CODE REVIEW

**Comment by 852Kerfunkle** [comment]
Regarding this code:

```go
// ConnectionInfo -
type ConnectionInfo struct {
	UsePreparedStatements bool        `json:"use_prepared_statements"`
	IsolationLevel        string      `json:"isolation_level"`
	DatabaseUrl           DatabaseUrl `json:"database_url,omitempty"`
}

// DatabaseUrl -
type DatabaseUrl string

// DatabaseUrlFromEnv -
type DatabaseUrlFromEnv struct {
	FromEnv string `json:"from_env"`
}

// UnmarshalJSON -
func (d *DatabaseUrl) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err == nil {
		*d = DatabaseUrl(s)
		return nil
	}

	var fromEnv DatabaseUrlFromEnv
	if err := json.Unmarshal(data, &fromEnv); err != nil {
		return err
	}

	*d = DatabaseUrl(fromEnv.FromEnv)
	return nil
}
```

I think that's broken? From env is not a connection string, it's just an environment variable name? Maybe I'm wrong, but when you serialise that, you'll get

```
"connection_info": {
    "database_url" : "ENV_VAR_NAME"
}
```

which will break your hasura config.

I think I'll just revert that to `interface{}`.

**Comment by 852Kerfunkle** [comment]
I also removed the `omitempty` on DatabaseUrl, I don't think it can be empty.

**Comment by aopoltorzhicky** [comment]
I don't think that removing anything is a good idea. I has already fixed database_url in previous commit

**Comment by aopoltorzhicky** [comment]
> Heya, I'm not sure that's good way to handle this. Imagine this case:
> Another services connection string is specified in an env var.
metadata indexer re-writes it to a plain string.
Env var is updated and the other service and hasura are restarted.
Hasura now points to the wrong database (assuming the other service does not add the source again).

I'm sorry to be late with the reply. I think that's not problem because different services has to use different environment variables. You should manipulate your connection string by env variables according to hasura docs. But in my opinion we should implement marshaling of `from_env` `DatabaseUrl` variant for that case. I'll take care of it in nearest future.

**Comment by 852Kerfunkle** [comment]
> I think that's not problem because different services has to use different environment variables. You should manipulate your connection string by env variables according to hasura docs.

Yes, but your change breaks this.

> But in my opinion we should implement marshaling of from_env DatabaseUrl variant for that case. I'll take care of it in nearest future.

Ok, works for me.

**Comment by 852Kerfunkle** [comment]
Regardless of your FromEnv change being somewhat broken, I'd appreciate if you merged this in the accompanying metadata PR, simply so I don't need to keep them up to date with other changes to master.

Thanks.

**Comment by m-kus** [comment]
LGTM

**Pull request merged**
